#!/bin/bash

read -p "Ingrese el primer número: " num1
read -p "Ingrese el segundo número: " num2

if [ "$num2" -eq 0 ]; then
    echo "No se permite una division por cero"
else
    if (( num1 % num2 == 0 )); then
        echo "Divisible"
    else
        echo "No divisible"
    fi
fi

#resultados terminal 
amara@penguin:~$ bash ejercicio5.txt
Ingrese el primer número: 3
Ingrese el segundo número: 1
Divisible

amara@penguin:~$ bash ejercicio5.txt
Ingrese el primer número: 2
Ingrese el segundo número: 0
